export const PROBLEMES_LIST_REQUEST = "PROBLEMES_LIST_REQUEST";
export const PROBLEMES_LIST_SUCCESS = "PROBLEMES_LIST_SUCCESS";
export const PROBLEMES_LIST_FAIL = "PROBLEMES_LIST_FAIL";

export const PROBLEMES_CREATE_REQUEST = "PROBLEMES_CREATE_REQUEST";
export const PROBLEMES_CREATE_SUCCESS = "PROBLEMES_CREATE_SUCCESS";
export const PROBLEMES_CREATE_FAIL = "PROBLEMES_CREATE_FAIL";

export const PROBLEMES_UPDATE_REQUEST = "PROBLEMES_UPDATE_REQUEST";
export const PROBLEMES_UPDATE_SUCCESS = "PROBLEMES_UPDATE_SUCCESS";
export const PROBLEMES_UPDATE_FAIL = "PROBLEMES_UPDATE_FAIL";

export const PROBLEMES_DELETE_REQUEST = "PROBLEMES_DELETE_REQUEST";
export const PROBLEMES_DELETE_SUCCESS = "PROBLEMES_DELETE_SUCCESS";
export const PROBLEMES_DELETE_FAIL = "PROBLEMES_DELETE_FAIL";